-- +goose Up
ALTER TABLE secrets DROP CONSTRAINT secrets_pkey;
ALTER TABLE secrets DROP COLUMN id;
ALTER TABLE secrets ADD COLUMN id UUID DEFAULT uuidv7() NOT NULL;
ALTER TABLE secrets ADD PRIMARY KEY (id);

-- +goose Down
ALTER TABLE secrets DROP CONSTRAINT secrets_pkey;
ALTER TABLE secrets DROP COLUMN id;
ALTER TABLE secrets ADD COLUMN id BIGSERIAL NOT NULL;
ALTER TABLE secrets ADD PRIMARY KEY (id);
