apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "secretli.fullname" . }}
  labels:
    {{- include "secretli.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
  S3_BUCKET: {{ .Values.config.s3Bucket | quote }}
  S3_REGION: {{ .Values.config.s3Region | quote }}
  S3_USE_SSL: {{ .Values.config.s3UseSSL | quote }}
  CLEANUP_INTERVAL: {{ .Values.config.cleanupInterval | quote }}
  SESSION_MAX_AGE: {{ .Values.config.sessionMaxAge | quote }}
  COOKIE_SECURE: {{ .Values.config.cookieSecure | quote }}
  ALLOWED_ORIGINS: {{ .Values.config.allowedOrigins | quote }}
  MAX_FILE_SIZE: {{ .Values.config.maxFileSize | quote }}
