apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "secretli.fullname" . }}
  labels:
    {{- include "secretli.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "secretli.selectorLabels" . | nindent 6 }}
