// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Secret struct {
	PublicID      string
	MetadataToken string
	DeletionToken string
	EncryptedMeta string
	BlobSize      int64
	BurnAfterRead bool
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	RetrievedAt   pgtype.Timestamptz
	BlobToken     string
}
