// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RetrievalSession struct {
	ID               int64
	PublicID         string
	SessionTokenHash string
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type Secret struct {
	PublicID          string
	MetadataTokenHash string
	BlobTokenHash     string
	DeletionTokenHash string
	EncryptedMeta     string
	BlobSize          int64
	BurnAfterRead     bool
	ExpiresAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	RetrievedAt       pgtype.Timestamptz
}

type UploadPart struct {
	SessionID  string
	PartNumber int32
	PartOffset int64
	PartSize   int64
	PartSha256 string
	Etag       string
	CreatedAt  pgtype.Timestamptz
}

type UploadSession struct {
	SessionID         string
	PublicID          string
	UploadTokenHash   string
	MetadataTokenHash string
	BlobTokenHash     string
	DeletionTokenHash string
	S3UploadID        string
	BlobSize          int64
	EncryptedMeta     string
	BurnAfterRead     bool
	SecretExpiresAt   pgtype.Timestamptz
	UploadExpiresAt   pgtype.Timestamptz
	State             string
	CreatedAt         pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
	AbortedAt         pgtype.Timestamptz
}
