// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimBurnAfterRead = `-- name: ClaimBurnAfterRead :execrows
UPDATE secrets SET retrieved_at = NOW()
WHERE public_id = $1
  AND blob_token = $2
  AND burn_after_read = true
  AND retrieved_at IS NULL
  AND expires_at > NOW()
`

type ClaimBurnAfterReadParams struct {
	PublicID  string
	BlobToken string
}

func (q *Queries) ClaimBurnAfterRead(ctx context.Context, arg ClaimBurnAfterReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimBurnAfterRead, arg.PublicID, arg.BlobToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createSecret = `-- name: CreateSecret :exec
INSERT INTO secrets (
    public_id, metadata_token, blob_token, deletion_token,
    encrypted_meta, blob_size,
    burn_after_read, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateSecretParams struct {
	PublicID      string
	MetadataToken string
	BlobToken     string
	DeletionToken string
	EncryptedMeta string
	BlobSize      int64
	BurnAfterRead bool
	ExpiresAt     pgtype.Timestamptz
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) error {
	_, err := q.db.Exec(ctx, createSecret,
		arg.PublicID,
		arg.MetadataToken,
		arg.BlobToken,
		arg.DeletionToken,
		arg.EncryptedMeta,
		arg.BlobSize,
		arg.BurnAfterRead,
		arg.ExpiresAt,
	)
	return err
}

const deleteSecret = `-- name: DeleteSecret :execrows
DELETE FROM secrets WHERE public_id = $1
`

func (q *Queries) DeleteSecret(ctx context.Context, publicID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSecret, publicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSecretByPublicID = `-- name: GetSecretByPublicID :one
SELECT public_id, metadata_token, blob_token, deletion_token,
    encrypted_meta, blob_size,
    burn_after_read,
    expires_at, created_at, retrieved_at
FROM secrets
WHERE public_id = $1 AND expires_at > NOW()
`

type GetSecretByPublicIDRow struct {
	PublicID      string
	MetadataToken string
	BlobToken     string
	DeletionToken string
	EncryptedMeta string
	BlobSize      int64
	BurnAfterRead bool
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	RetrievedAt   pgtype.Timestamptz
}

func (q *Queries) GetSecretByPublicID(ctx context.Context, publicID string) (GetSecretByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getSecretByPublicID, publicID)
	var i GetSecretByPublicIDRow
	err := row.Scan(
		&i.PublicID,
		&i.MetadataToken,
		&i.BlobToken,
		&i.DeletionToken,
		&i.EncryptedMeta,
		&i.BlobSize,
		&i.BurnAfterRead,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RetrievedAt,
	)
	return i, err
}

const selectExpiredForCleanup = `-- name: SelectExpiredForCleanup :many
SELECT public_id FROM secrets
WHERE expires_at < NOW()
   OR (burn_after_read = true AND retrieved_at IS NOT NULL)
FOR UPDATE SKIP LOCKED
`

func (q *Queries) SelectExpiredForCleanup(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, selectExpiredForCleanup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var public_id string
		if err := rows.Scan(&public_id); err != nil {
			return nil, err
		}
		items = append(items, public_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
