// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfers.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimTransfer = `-- name: ClaimTransfer :one
UPDATE transfers
SET state               = 'claimed',
    receiver_token_hash = $1,
    claimed_at          = $2
WHERE nameplate = $3
  AND state = 'open'
  AND expires_at > $2
RETURNING transfer_id, nameplate, sender_token_hash, receiver_token_hash, state, close_reason, created_at, expires_at, claimed_at, closed_at
`

type ClaimTransferParams struct {
	ReceiverTokenHash pgtype.Text
	NowAt             pgtype.Timestamptz
	Nameplate         int32
}

func (q *Queries) ClaimTransfer(ctx context.Context, arg ClaimTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, claimTransfer, arg.ReceiverTokenHash, arg.NowAt, arg.Nameplate)
	var i Transfer
	err := row.Scan(
		&i.TransferID,
		&i.Nameplate,
		&i.SenderTokenHash,
		&i.ReceiverTokenHash,
		&i.State,
		&i.CloseReason,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.ClosedAt,
	)
	return i, err
}

const claimedTransferExists = `-- name: ClaimedTransferExists :one
SELECT EXISTS (
    SELECT 1
    FROM transfers
    WHERE nameplate = $1
      AND state = 'claimed'
      AND expires_at > $2
)
`

type ClaimedTransferExistsParams struct {
	Nameplate int32
	NowAt     pgtype.Timestamptz
}

func (q *Queries) ClaimedTransferExists(ctx context.Context, arg ClaimedTransferExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, claimedTransferExists, arg.Nameplate, arg.NowAt)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const closeExpiredActiveTransfers = `-- name: CloseExpiredActiveTransfers :exec
UPDATE transfers
SET state        = 'closed',
    close_reason = 'expired',
    closed_at    = $1
WHERE state IN ('open', 'claimed')
  AND expires_at <= $1
`

// Frees the nameplates of transfers that ran out before cleanup got to them.
func (q *Queries) CloseExpiredActiveTransfers(ctx context.Context, nowAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, closeExpiredActiveTransfers, nowAt)
	return err
}

const closeTransfer = `-- name: CloseTransfer :execrows
UPDATE transfers
SET state        = 'closed',
    close_reason = $1,
    closed_at    = $2
WHERE transfer_id = $3
  AND state IN ('open', 'claimed')
`

type CloseTransferParams struct {
	CloseReason pgtype.Text
	NowAt       pgtype.Timestamptz
	TransferID  string
}

func (q *Queries) CloseTransfer(ctx context.Context, arg CloseTransferParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeTransfer, arg.CloseReason, arg.NowAt, arg.TransferID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createTransfer = `-- name: CreateTransfer :exec
INSERT INTO transfers (
    transfer_id,
    nameplate,
    sender_token_hash,
    state,
    created_at,
    expires_at
)
VALUES (
    $1, $2, $3, 'open', $4, $5
)
`

type CreateTransferParams struct {
	TransferID      string
	Nameplate       int32
	SenderTokenHash string
	CreatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) error {
	_, err := q.db.Exec(ctx, createTransfer,
		arg.TransferID,
		arg.Nameplate,
		arg.SenderTokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createTransferMessage = `-- name: CreateTransferMessage :execrows
INSERT INTO transfer_messages (
    transfer_id,
    side,
    phase,
    data,
    created_at
)
VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (transfer_id, side, phase) DO NOTHING
`

type CreateTransferMessageParams struct {
	TransferID string
	Side       string
	Phase      string
	Data       []byte
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateTransferMessage(ctx context.Context, arg CreateTransferMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, createTransferMessage,
		arg.TransferID,
		arg.Side,
		arg.Phase,
		arg.Data,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEndedTransfers = `-- name: DeleteEndedTransfers :execrows
DELETE FROM transfers
WHERE expires_at < $1
   OR closed_at < $1
`

func (q *Queries) DeleteEndedTransfers(ctx context.Context, endedBefore pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEndedTransfers, endedBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTransfer = `-- name: GetTransfer :one
SELECT transfer_id, nameplate, sender_token_hash, receiver_token_hash, state, close_reason, created_at, expires_at, claimed_at, closed_at
FROM transfers
WHERE transfer_id = $1
`

func (q *Queries) GetTransfer(ctx context.Context, transferID string) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransfer, transferID)
	var i Transfer
	err := row.Scan(
		&i.TransferID,
		&i.Nameplate,
		&i.SenderTokenHash,
		&i.ReceiverTokenHash,
		&i.State,
		&i.CloseReason,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getTransferMessage = `-- name: GetTransferMessage :one
SELECT transfer_id, side, phase, data, created_at
FROM transfer_messages
WHERE transfer_id = $1
  AND side = $2
  AND phase = $3
`

type GetTransferMessageParams struct {
	TransferID string
	Side       string
	Phase      string
}

func (q *Queries) GetTransferMessage(ctx context.Context, arg GetTransferMessageParams) (TransferMessage, error) {
	row := q.db.QueryRow(ctx, getTransferMessage, arg.TransferID, arg.Side, arg.Phase)
	var i TransferMessage
	err := row.Scan(
		&i.TransferID,
		&i.Side,
		&i.Phase,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const lockTransferNameplates = `-- name: LockTransferNameplates :exec
SELECT pg_advisory_xact_lock(7302101)
`

// Serializes nameplate allocation across replicas for one transaction, so
// concurrent creates take consecutive numbers instead of racing for one.
func (q *Queries) LockTransferNameplates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockTransferNameplates)
	return err
}

const nextFreeNameplate = `-- name: NextFreeNameplate :one
SELECT n::INTEGER AS nameplate
FROM generate_series(1, $1::INTEGER) AS n
WHERE NOT EXISTS (
    SELECT 1
    FROM transfers t
    WHERE t.nameplate = n
      AND t.state IN ('open', 'claimed')
)
ORDER BY n
LIMIT 1
`

func (q *Queries) NextFreeNameplate(ctx context.Context, maxNameplate int32) (int32, error) {
	row := q.db.QueryRow(ctx, nextFreeNameplate, maxNameplate)
	var nameplate int32
	err := row.Scan(&nameplate)
	return nameplate, err
}
