// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Secret struct {
	ID                 int64
	PublicID           string
	RetrievalTokenHash string
	DeletionTokenHash  string
	EncryptedData      pgtype.Text
	Nonce              string
	SecretType         string
	StorageKey         pgtype.Text
	EncryptedFilename  pgtype.Text
	EncryptedSize      pgtype.Int8
	BurnAfterRead      bool
	PasswordProtected  bool
	ExpiresAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	RetrievedAt        pgtype.Timestamptz
}
