// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: secrets.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSecret = `-- name: CreateSecret :one
INSERT INTO secrets (
    public_id, retrieval_token_hash, deletion_token_hash,
    encrypted_data, nonce, secret_type,
    storage_key, encrypted_filename, encrypted_size,
    burn_after_read, password_protected, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id
`

type CreateSecretParams struct {
	PublicID           string
	RetrievalTokenHash string
	DeletionTokenHash  string
	EncryptedData      pgtype.Text
	Nonce              string
	SecretType         string
	StorageKey         pgtype.Text
	EncryptedFilename  pgtype.Text
	EncryptedSize      pgtype.Int8
	BurnAfterRead      bool
	PasswordProtected  bool
	ExpiresAt          pgtype.Timestamptz
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSecret,
		arg.PublicID,
		arg.RetrievalTokenHash,
		arg.DeletionTokenHash,
		arg.EncryptedData,
		arg.Nonce,
		arg.SecretType,
		arg.StorageKey,
		arg.EncryptedFilename,
		arg.EncryptedSize,
		arg.BurnAfterRead,
		arg.PasswordProtected,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredSecrets = `-- name: DeleteExpiredSecrets :many
DELETE FROM secrets WHERE expires_at < NOW()
RETURNING storage_key
`

func (q *Queries) DeleteExpiredSecrets(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, deleteExpiredSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var storage_key pgtype.Text
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSecret = `-- name: DeleteSecret :execrows
DELETE FROM secrets WHERE public_id = $1
`

func (q *Queries) DeleteSecret(ctx context.Context, publicID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSecret, publicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAndDeleteSecretByPublicID = `-- name: GetAndDeleteSecretByPublicID :one
DELETE FROM secrets
WHERE public_id = $1 AND expires_at > NOW()
RETURNING id, public_id, retrieval_token_hash, deletion_token_hash,
    encrypted_data, nonce, secret_type,
    storage_key, encrypted_filename, encrypted_size,
    burn_after_read, password_protected,
    expires_at, created_at, retrieved_at
`

type GetAndDeleteSecretByPublicIDRow struct {
	ID                 uuid.UUID
	PublicID           string
	RetrievalTokenHash string
	DeletionTokenHash  string
	EncryptedData      pgtype.Text
	Nonce              string
	SecretType         string
	StorageKey         pgtype.Text
	EncryptedFilename  pgtype.Text
	EncryptedSize      pgtype.Int8
	BurnAfterRead      bool
	PasswordProtected  bool
	ExpiresAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	RetrievedAt        pgtype.Timestamptz
}

func (q *Queries) GetAndDeleteSecretByPublicID(ctx context.Context, publicID string) (GetAndDeleteSecretByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getAndDeleteSecretByPublicID, publicID)
	var i GetAndDeleteSecretByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.RetrievalTokenHash,
		&i.DeletionTokenHash,
		&i.EncryptedData,
		&i.Nonce,
		&i.SecretType,
		&i.StorageKey,
		&i.EncryptedFilename,
		&i.EncryptedSize,
		&i.BurnAfterRead,
		&i.PasswordProtected,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RetrievedAt,
	)
	return i, err
}

const getSecretByPublicID = `-- name: GetSecretByPublicID :one
SELECT id, public_id, retrieval_token_hash, deletion_token_hash,
    encrypted_data, nonce, secret_type,
    storage_key, encrypted_filename, encrypted_size,
    burn_after_read, password_protected,
    expires_at, created_at, retrieved_at
FROM secrets
WHERE public_id = $1 AND expires_at > NOW()
`

type GetSecretByPublicIDRow struct {
	ID                 uuid.UUID
	PublicID           string
	RetrievalTokenHash string
	DeletionTokenHash  string
	EncryptedData      pgtype.Text
	Nonce              string
	SecretType         string
	StorageKey         pgtype.Text
	EncryptedFilename  pgtype.Text
	EncryptedSize      pgtype.Int8
	BurnAfterRead      bool
	PasswordProtected  bool
	ExpiresAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	RetrievedAt        pgtype.Timestamptz
}

func (q *Queries) GetSecretByPublicID(ctx context.Context, publicID string) (GetSecretByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getSecretByPublicID, publicID)
	var i GetSecretByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.RetrievalTokenHash,
		&i.DeletionTokenHash,
		&i.EncryptedData,
		&i.Nonce,
		&i.SecretType,
		&i.StorageKey,
		&i.EncryptedFilename,
		&i.EncryptedSize,
		&i.BurnAfterRead,
		&i.PasswordProtected,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RetrievedAt,
	)
	return i, err
}

const setSecretRetrievedAt = `-- name: SetSecretRetrievedAt :exec
UPDATE secrets SET retrieved_at = NOW()
WHERE public_id = $1 AND retrieved_at IS NULL
`

func (q *Queries) SetSecretRetrievedAt(ctx context.Context, publicID string) error {
	_, err := q.db.Exec(ctx, setSecretRetrievedAt, publicID)
	return err
}
